# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_launch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_launch.setGeometry(QtCore.QRect(380, 320, 171, 41))
        self.btn_launch.setObjectName("btn_launch")
        self.TabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.TabMenu.setGeometry(QtCore.QRect(10, 10, 541, 301))
        self.TabMenu.setObjectName("TabMenu")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_parameters)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 10, 351, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chk_param_autokick = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_autokick.setObjectName("chk_param_autokick")
        self.verticalLayout_2.addWidget(self.chk_param_autokick)
        self.chk_param_gogodemo = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_gogodemo.setObjectName("chk_param_gogodemo")
        self.verticalLayout_2.addWidget(self.chk_param_gogodemo)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.chk_param_nop2p = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nop2p.setObjectName("chk_param_nop2p")
        self.verticalLayout_2.addWidget(self.chk_param_nop2p)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_param_nopause = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nopause.setObjectName("chk_param_nopause")
        self.verticalLayout.addWidget(self.chk_param_nopause)
        self.chk_param_nouser = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nouser.setObjectName("chk_param_nouser")
        self.verticalLayout.addWidget(self.chk_param_nouser)
        self.chk_param_sessionlog = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sessionlog.setObjectName("chk_param_sessionlog")
        self.verticalLayout.addWidget(self.chk_param_sessionlog)
        self.chk_param_nointro = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nointro.setObjectName("chk_param_nointro")
        self.verticalLayout.addWidget(self.chk_param_nointro)
        self.chk_param_nogamma = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nogamma.setObjectName("chk_param_nogamma")
        self.verticalLayout.addWidget(self.chk_param_nogamma)
        self.chk_param_sload = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sload.setObjectName("chk_param_sload")
        self.verticalLayout.addWidget(self.chk_param_sload)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.listWidget = QtWidgets.QListWidget(self.tab_parameters)
        self.listWidget.setGeometry(QtCore.QRect(2, 9, 161, 201))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_parameters)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(3, 215, 160, 36))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/up-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/resources/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttons/resources/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.TabMenu.addTab(self.tab_parameters, "")
        self.tab_cars = QtWidgets.QWidget()
        self.tab_cars.setObjectName("tab_cars")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_cars)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 531, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.TabMenu.addTab(self.tab_cars, "")
        self.tab_tracks = QtWidgets.QWidget()
        self.tab_tracks.setObjectName("tab_tracks")
        self.TabMenu.addTab(self.tab_tracks, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 556, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_RVGL_Path = QtWidgets.QAction(MainWindow)
        self.actionChange_RVGL_Path.setObjectName("actionChange_RVGL_Path")
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionChange_RVGL_Path)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.TabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.TabMenu, self.btn_launch)
        MainWindow.setTabOrder(self.btn_launch, self.chk_param_autokick)
        MainWindow.setTabOrder(self.chk_param_autokick, self.chk_param_gogodemo)
        MainWindow.setTabOrder(self.chk_param_gogodemo, self.chk_param_nop2p)
        MainWindow.setTabOrder(self.chk_param_nop2p, self.chk_param_nopause)
        MainWindow.setTabOrder(self.chk_param_nopause, self.chk_param_nouser)
        MainWindow.setTabOrder(self.chk_param_nouser, self.chk_param_sessionlog)
        MainWindow.setTabOrder(self.chk_param_sessionlog, self.chk_param_sload)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RVGL Assistant"))
        self.btn_launch.setText(_translate("MainWindow", "Launch RVGL"))
        self.chk_param_autokick.setText(_translate("MainWindow", "Autokick"))
        self.chk_param_gogodemo.setText(_translate("MainWindow", "Gogodemo"))
        self.checkBox.setText(_translate("MainWindow", "Localport"))
        self.lineEdit.setToolTip(_translate("MainWindow", "Localport"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Port"))
        self.checkBox_2.setText(_translate("MainWindow", "Lobby"))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "Localport"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "IP Address"))
        self.chk_param_nop2p.setText(_translate("MainWindow", "Nop2p"))
        self.chk_param_nopause.setText(_translate("MainWindow", "Nopause"))
        self.chk_param_nouser.setText(_translate("MainWindow", "Nouser"))
        self.chk_param_sessionlog.setText(_translate("MainWindow", "Sessionlog"))
        self.chk_param_nointro.setText(_translate("MainWindow", "Nointro"))
        self.chk_param_nogamma.setText(_translate("MainWindow", "Nogamma"))
        self.chk_param_sload.setText(_translate("MainWindow", "Sload"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_parameters), _translate("MainWindow", "Parameters"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Box"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_cars), _translate("MainWindow", "Cars"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_tracks), _translate("MainWindow", "Tracks"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSettings.setTitle(_translate("MainWindow", "Setti&ngs"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionChange_RVGL_Path.setText(_translate("MainWindow", "&Change RVGL Path"))

import gui_resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

