# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_launch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_launch.setGeometry(QtCore.QRect(370, 240, 171, 41))
        self.btn_launch.setObjectName("btn_launch")
        self.TabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.TabMenu.setGeometry(QtCore.QRect(10, 10, 531, 221))
        self.TabMenu.setObjectName("TabMenu")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_parameters)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chk_param_autokick = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_autokick.setObjectName("chk_param_autokick")
        self.verticalLayout_2.addWidget(self.chk_param_autokick)
        self.chk_param_gogodemo = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_gogodemo.setObjectName("chk_param_gogodemo")
        self.verticalLayout_2.addWidget(self.chk_param_gogodemo)
        self.chk_param_nogamma = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nogamma.setObjectName("chk_param_nogamma")
        self.verticalLayout_2.addWidget(self.chk_param_nogamma)
        self.chk_param_nointro = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nointro.setObjectName("chk_param_nointro")
        self.verticalLayout_2.addWidget(self.chk_param_nointro)
        self.chk_param_nop2p = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nop2p.setObjectName("chk_param_nop2p")
        self.verticalLayout_2.addWidget(self.chk_param_nop2p)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_param_nopause = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nopause.setObjectName("chk_param_nopause")
        self.verticalLayout.addWidget(self.chk_param_nopause)
        self.chk_param_nouser = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nouser.setObjectName("chk_param_nouser")
        self.verticalLayout.addWidget(self.chk_param_nouser)
        self.chk_param_sessionlog = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sessionlog.setObjectName("chk_param_sessionlog")
        self.verticalLayout.addWidget(self.chk_param_sessionlog)
        self.chk_param_sload = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sload.setObjectName("chk_param_sload")
        self.verticalLayout.addWidget(self.chk_param_sload)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.TabMenu.addTab(self.tab_parameters, "")
        self.tab_cars = QtWidgets.QWidget()
        self.tab_cars.setObjectName("tab_cars")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_cars)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 521, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.TabMenu.addTab(self.tab_cars, "")
        self.tab_tracks = QtWidgets.QWidget()
        self.tab_tracks.setObjectName("tab_tracks")
        self.TabMenu.addTab(self.tab_tracks, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 548, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_RVGL_Path = QtWidgets.QAction(MainWindow)
        self.actionChange_RVGL_Path.setObjectName("actionChange_RVGL_Path")
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionChange_RVGL_Path)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.TabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.TabMenu, self.btn_launch)
        MainWindow.setTabOrder(self.btn_launch, self.chk_param_autokick)
        MainWindow.setTabOrder(self.chk_param_autokick, self.chk_param_nogamma)
        MainWindow.setTabOrder(self.chk_param_nogamma, self.chk_param_gogodemo)
        MainWindow.setTabOrder(self.chk_param_gogodemo, self.chk_param_nointro)
        MainWindow.setTabOrder(self.chk_param_nointro, self.chk_param_nop2p)
        MainWindow.setTabOrder(self.chk_param_nop2p, self.chk_param_nopause)
        MainWindow.setTabOrder(self.chk_param_nopause, self.chk_param_nouser)
        MainWindow.setTabOrder(self.chk_param_nouser, self.chk_param_sessionlog)
        MainWindow.setTabOrder(self.chk_param_sessionlog, self.chk_param_sload)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RVGL Assistant"))
        self.btn_launch.setText(_translate("MainWindow", "Launch RVGL"))
        self.chk_param_autokick.setText(_translate("MainWindow", "Autokick"))
        self.chk_param_gogodemo.setText(_translate("MainWindow", "Gogodemo"))
        self.chk_param_nogamma.setText(_translate("MainWindow", "Nogamma"))
        self.chk_param_nointro.setText(_translate("MainWindow", "Nointro"))
        self.chk_param_nop2p.setText(_translate("MainWindow", "Nop2p"))
        self.chk_param_nopause.setText(_translate("MainWindow", "Nopause"))
        self.chk_param_nouser.setText(_translate("MainWindow", "Nouser"))
        self.chk_param_sessionlog.setText(_translate("MainWindow", "Sessionlog"))
        self.chk_param_sload.setText(_translate("MainWindow", "Sload"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_parameters), _translate("MainWindow", "Parameters"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Box"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_cars), _translate("MainWindow", "Cars"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_tracks), _translate("MainWindow", "Tracks"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSettings.setTitle(_translate("MainWindow", "Setti&ngs"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionChange_RVGL_Path.setText(_translate("MainWindow", "Change RVGL Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

