# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_launch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_launch.setGeometry(QtCore.QRect(560, 350, 171, 41))
        self.btn_launch.setObjectName("btn_launch")
        self.TabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.TabMenu.setGeometry(QtCore.QRect(10, 10, 721, 331))
        self.TabMenu.setObjectName("TabMenu")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_parameters)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 10, 547, 282))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_parameters = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_parameters.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_parameters.setObjectName("horizontalLayout_parameters")
        self.layout_params_1 = QtWidgets.QVBoxLayout()
        self.layout_params_1.setObjectName("layout_params_1")
        self.chk_param_autokick = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_autokick.setObjectName("chk_param_autokick")
        self.layout_params_1.addWidget(self.chk_param_autokick)
        self.chk_param_gogodemo = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_gogodemo.setObjectName("chk_param_gogodemo")
        self.layout_params_1.addWidget(self.chk_param_gogodemo)
        self.chk_param_lobby = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_param_lobby.sizePolicy().hasHeightForWidth())
        self.chk_param_lobby.setSizePolicy(sizePolicy)
        self.chk_param_lobby.setObjectName("chk_param_lobby")
        self.layout_params_1.addWidget(self.chk_param_lobby)
        self.txt_ip_address = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ip_address.sizePolicy().hasHeightForWidth())
        self.txt_ip_address.setSizePolicy(sizePolicy)
        self.txt_ip_address.setText("")
        self.txt_ip_address.setReadOnly(True)
        self.txt_ip_address.setObjectName("txt_ip_address")
        self.layout_params_1.addWidget(self.txt_ip_address)
        self.chk_param_multisample = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_param_multisample.sizePolicy().hasHeightForWidth())
        self.chk_param_multisample.setSizePolicy(sizePolicy)
        self.chk_param_multisample.setObjectName("chk_param_multisample")
        self.layout_params_1.addWidget(self.chk_param_multisample)
        self.txt_num_samples = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_num_samples.sizePolicy().hasHeightForWidth())
        self.txt_num_samples.setSizePolicy(sizePolicy)
        self.txt_num_samples.setText("")
        self.txt_num_samples.setReadOnly(True)
        self.txt_num_samples.setObjectName("txt_num_samples")
        self.layout_params_1.addWidget(self.txt_num_samples)
        self.chk_param_nointro = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nointro.setObjectName("chk_param_nointro")
        self.layout_params_1.addWidget(self.chk_param_nointro)
        self.chk_param_nogamma = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nogamma.setObjectName("chk_param_nogamma")
        self.layout_params_1.addWidget(self.chk_param_nogamma)
        self.layout_params_4 = QtWidgets.QHBoxLayout()
        self.layout_params_4.setObjectName("layout_params_4")
        self.chk_param_localport = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_param_localport.sizePolicy().hasHeightForWidth())
        self.chk_param_localport.setSizePolicy(sizePolicy)
        self.chk_param_localport.setObjectName("chk_param_localport")
        self.layout_params_4.addWidget(self.chk_param_localport)
        self.txt_port = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_port.sizePolicy().hasHeightForWidth())
        self.txt_port.setSizePolicy(sizePolicy)
        self.txt_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.txt_port.setReadOnly(True)
        self.txt_port.setClearButtonEnabled(False)
        self.txt_port.setObjectName("txt_port")
        self.layout_params_4.addWidget(self.txt_port)
        self.layout_params_1.addLayout(self.layout_params_4)
        self.horizontalLayout_parameters.addLayout(self.layout_params_1)
        self.layout_params_2 = QtWidgets.QVBoxLayout()
        self.layout_params_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layout_params_2.setObjectName("layout_params_2")
        self.chk_param_nop2p = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nop2p.setObjectName("chk_param_nop2p")
        self.layout_params_2.addWidget(self.chk_param_nop2p)
        self.chk_param_nopause = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nopause.setObjectName("chk_param_nopause")
        self.layout_params_2.addWidget(self.chk_param_nopause)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.layout_params_2.addWidget(self.checkBox_6)
        self.chk_param_nouser = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_nouser.setObjectName("chk_param_nouser")
        self.layout_params_2.addWidget(self.chk_param_nouser)
        self.layout_params_5 = QtWidgets.QHBoxLayout()
        self.layout_params_5.setObjectName("layout_params_5")
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.layout_params_5.addWidget(self.checkBox_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(92, 16777215))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.layout_params_5.addWidget(self.lineEdit_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_params_5.addItem(spacerItem)
        self.layout_params_2.addLayout(self.layout_params_5)
        self.layout_params_6 = QtWidgets.QHBoxLayout()
        self.layout_params_6.setObjectName("layout_params_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.layout_params_6.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.layout_params_6.addWidget(self.checkBox_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_params_6.addItem(spacerItem1)
        self.layout_params_2.addLayout(self.layout_params_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(80, 32))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(80, 32))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.layout_params_2.addLayout(self.horizontalLayout_4)
        self.chk_param_sessionlog = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sessionlog.setObjectName("chk_param_sessionlog")
        self.layout_params_2.addWidget(self.chk_param_sessionlog)
        self.chk_param_sload = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_sload.setObjectName("chk_param_sload")
        self.layout_params_2.addWidget(self.chk_param_sload)
        self.horizontalLayout_parameters.addLayout(self.layout_params_2)
        self.layout_params_3 = QtWidgets.QVBoxLayout()
        self.layout_params_3.setObjectName("layout_params_3")
        self.chk_param_dev = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_dev.setObjectName("chk_param_dev")
        self.layout_params_3.addWidget(self.chk_param_dev)
        self.layout_params_7 = QtWidgets.QHBoxLayout()
        self.layout_params_7.setObjectName("layout_params_7")
        self.chk_param_alpharef = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_param_alpharef.sizePolicy().hasHeightForWidth())
        self.chk_param_alpharef.setSizePolicy(sizePolicy)
        self.chk_param_alpharef.setObjectName("chk_param_alpharef")
        self.layout_params_7.addWidget(self.chk_param_alpharef)
        self.txt_alpharef = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_alpharef.sizePolicy().hasHeightForWidth())
        self.txt_alpharef.setSizePolicy(sizePolicy)
        self.txt_alpharef.setMaximumSize(QtCore.QSize(80, 16777215))
        self.txt_alpharef.setReadOnly(True)
        self.txt_alpharef.setClearButtonEnabled(False)
        self.txt_alpharef.setObjectName("txt_alpharef")
        self.layout_params_7.addWidget(self.txt_alpharef)
        self.layout_params_3.addLayout(self.layout_params_7)
        self.chk_param_cubevisi = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chk_param_cubevisi.setObjectName("chk_param_cubevisi")
        self.layout_params_3.addWidget(self.chk_param_cubevisi)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_params_3.addItem(spacerItem3)
        self.horizontalLayout_parameters.addLayout(self.layout_params_3)
        self.lst_profiles = QtWidgets.QListWidget(self.tab_parameters)
        self.lst_profiles.setGeometry(QtCore.QRect(2, 9, 161, 241))
        self.lst_profiles.setObjectName("lst_profiles")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_parameters)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(4, 255, 160, 36))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_up = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/resources/up-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon)
        self.btn_up.setObjectName("btn_up")
        self.horizontalLayout.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_down.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/resources/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon1)
        self.btn_down.setObjectName("btn_down")
        self.horizontalLayout.addWidget(self.btn_down)
        self.btn_delete = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_delete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/resources/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon2)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_save = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_save.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttons/resources/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon3)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.TabMenu.addTab(self.tab_parameters, "")
        self.tab_cars = QtWidgets.QWidget()
        self.tab_cars.setObjectName("tab_cars")
        self.tbl_cars = QtWidgets.QTableWidget(self.tab_cars)
        self.tbl_cars.setGeometry(QtCore.QRect(0, 50, 711, 241))
        self.tbl_cars.setObjectName("tbl_cars")
        self.tbl_cars.setColumnCount(3)
        self.tbl_cars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cars.setHorizontalHeaderItem(2, item)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_cars)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 10, 531, 34))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.txt_srch_cars = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.txt_srch_cars.setObjectName("txt_srch_cars")
        self.horizontalLayout_9.addWidget(self.txt_srch_cars)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.TabMenu.addTab(self.tab_cars, "")
        self.tab_tracks = QtWidgets.QWidget()
        self.tab_tracks.setObjectName("tab_tracks")
        self.tbl_tracks = QtWidgets.QTableWidget(self.tab_tracks)
        self.tbl_tracks.setGeometry(QtCore.QRect(0, 50, 711, 241))
        self.tbl_tracks.setObjectName("tbl_tracks")
        self.tbl_tracks.setColumnCount(2)
        self.tbl_tracks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tracks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tracks.setHorizontalHeaderItem(1, item)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_tracks)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 10, 531, 34))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.txt_srch_tracks = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.txt_srch_tracks.setObjectName("txt_srch_tracks")
        self.horizontalLayout_10.addWidget(self.txt_srch_tracks)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.TabMenu.addTab(self.tab_tracks, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 737, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_RVGL_Path = QtWidgets.QAction(MainWindow)
        self.actionChange_RVGL_Path.setObjectName("actionChange_RVGL_Path")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuFile.addAction(self.actionAbout_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionChange_RVGL_Path)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.TabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.TabMenu, self.btn_launch)
        MainWindow.setTabOrder(self.btn_launch, self.chk_param_autokick)
        MainWindow.setTabOrder(self.chk_param_autokick, self.chk_param_gogodemo)
        MainWindow.setTabOrder(self.chk_param_gogodemo, self.chk_param_nopause)
        MainWindow.setTabOrder(self.chk_param_nopause, self.chk_param_sessionlog)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RVGL Assistant"))
        self.btn_launch.setText(_translate("MainWindow", "Launch RVGL"))
        self.chk_param_autokick.setText(_translate("MainWindow", "-autokick"))
        self.chk_param_gogodemo.setText(_translate("MainWindow", "-gogodemo"))
        self.chk_param_lobby.setText(_translate("MainWindow", "-lobby"))
        self.txt_ip_address.setToolTip(_translate("MainWindow", "Localport"))
        self.txt_ip_address.setPlaceholderText(_translate("MainWindow", "IP Address"))
        self.chk_param_multisample.setText(_translate("MainWindow", "-multisample"))
        self.txt_num_samples.setToolTip(_translate("MainWindow", "Localport"))
        self.txt_num_samples.setPlaceholderText(_translate("MainWindow", "Num samples"))
        self.chk_param_nointro.setText(_translate("MainWindow", "-nointro"))
        self.chk_param_nogamma.setText(_translate("MainWindow", "-nogamma"))
        self.chk_param_localport.setText(_translate("MainWindow", "-localport"))
        self.txt_port.setToolTip(_translate("MainWindow", "Localport"))
        self.txt_port.setPlaceholderText(_translate("MainWindow", "Port"))
        self.chk_param_nop2p.setText(_translate("MainWindow", "-nop2p"))
        self.chk_param_nopause.setText(_translate("MainWindow", "-nopause"))
        self.checkBox_6.setText(_translate("MainWindow", "-nosound"))
        self.chk_param_nouser.setText(_translate("MainWindow", "-nouser"))
        self.checkBox_4.setText(_translate("MainWindow", "-profile"))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "Localport"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Name"))
        self.checkBox_5.setText(_translate("MainWindow", "-res"))
        self.checkBox_7.setText(_translate("MainWindow", "-window"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Height"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Width"))
        self.chk_param_sessionlog.setText(_translate("MainWindow", "-sessionlog"))
        self.chk_param_sload.setText(_translate("MainWindow", "-sload"))
        self.chk_param_dev.setText(_translate("MainWindow", "-dev"))
        self.chk_param_alpharef.setText(_translate("MainWindow", "-alpharef"))
        self.txt_alpharef.setToolTip(_translate("MainWindow", "Localport"))
        self.txt_alpharef.setPlaceholderText(_translate("MainWindow", "0 to 256"))
        self.chk_param_cubevisi.setText(_translate("MainWindow", "cubevisi"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_parameters), _translate("MainWindow", "Parameters"))
        item = self.tbl_cars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Box"))
        item = self.tbl_cars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tbl_cars.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_cars), _translate("MainWindow", "Cars"))
        item = self.tbl_tracks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tbl_tracks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.label_2.setText(_translate("MainWindow", "Search:"))
        self.TabMenu.setTabText(self.TabMenu.indexOf(self.tab_tracks), _translate("MainWindow", "Tracks"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSettings.setTitle(_translate("MainWindow", "Setti&ngs"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionChange_RVGL_Path.setText(_translate("MainWindow", "&Change RVGL Path"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))

import gui_resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

